# Generated by Django 5.2.7 on 2025-12-08 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz_app.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attempt',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
