# Generated by Django 5.2.7 on 2025-12-10 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_category_default_level_question_generated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='default_level',
        ),
        migrations.RemoveField(
            model_name='question',
            name='generated',
        ),
        migrations.AddField(
            model_name='attempt',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(default='easy', max_length=20),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz_app.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_app.category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
